### ISSUE TITLE
[SMI] Support SMI Conformance - refactor for new meshes.proto

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-istio#108]
**Current Behavior**
Meshes.proto (defined in `meshery` repo) has been updated to account for SMI Conformance use cases.

**Desired Behavior**
The Meshery adapter for Istio needs to be updated to be compatible with these changes and support the new "SMI Conformance Tests" `VALIDATION` operation.

**Comment by KarenEfereyan** [comment]
@lee can I try my hands on this?

**Comment by KarenEfereyan** [comment]
Can I get a little more context for this issue?

**Comment by leecalcote** [comment]
@KarenEfereyan Thanks for taking a look at this issue. I left the "help wanted" label off of this issue, because it is a difficult item. It involves golang, protobuf, grpc and coordination between multiple repos with multiple release versions. Contributors new to golang often start with a [component/mesheryctl](https://github.com/layer5io/meshery/issues?q=is%3Aissue+is%3Aopen+label%3Acomponent%2Fmesheryctl) issue, because it is a smaller codebase to reason over and the commands are somewhat procedural in nature.

**Comment by KarenEfereyan** [comment]
I will leave it for now
