### ISSUE TITLE
Auto-configure Istio Ingress Gateway networking: LoadBalancer or NodePort

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-istio#127]
**Current Behavior**
Perform a TCP check to connect to the IP address of the ing gw

**Desired Behavior**
Confirm that the IP address of the ingress gw svc is accessible. Fallback to NodePort config otherwise.

**Comment by vineethvanga18** [comment]
@leecalcote I will take this up

**Comment by leecalcote** [comment]
@vineethvanga18 this is a great operation to enable invocation from MeshMap. There is a collection of operations that you'll find under the "Apply Service Mesh Configuration" category. @anirudhjain75 will you speak with @vineethvanga18 about how to invoke such operations?

**Comment by leecalcote** [comment]
As you consider how to make this flexible, @vineethvanga18 note the related ask here - https://github.com/layer5io/meshery-istio/issues/2

**Comment by vineethvanga18** [comment]
@leecalcote okay! I will investigate more on this

**Comment by kumarabd** [comment]
This has been done in meshkit.
