### ISSUE TITLE
[Patterns] Add another step in the hierarchy for component name

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-istio#229]
**Current Behavior**
Current OAM spec namespacing is not granular enough.

**Desired Behavior**
Another step in the hierarchical namespacing of OAM specs based on registering component name.

e.g. `prometheus.istio.meshery.layer5.io`

Perhaps, "addon" is accounted for in the `type` of its definition.

**Comment by leecalcote** [comment]
I think this has been completed. Please confirm.

**Comment by utkarsh-pro** [comment]
No @leecalcote, this isn't yet complete. Reopening this issue...
