### ISSUE TITLE
Upgrade meshkit errors

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery-istio#235]
**Description**
Port meshkit errors to the new error utility function. Instructions covered here, layer5io/meshkit#48

**Comment by Shreyas220** [comment]
Hi, can i try this ?

**Comment by kumarabd** [comment]
Sure @Shreyas220 , lemme know if you need more info

**Comment by Shreyas220** [comment]
yes, @kumarabd
shall i ping you in slack ?
please mention your username there

**Comment by Shreyas220** [comment]
@kumarabd AFAK this issue is already done

**Comment by kumarabd** [comment]
I see its already done by @dhruv0000 , perhaps you could pick up a similar issue on https://github.com/meshery/meshery-operator/issues/170 @Shreyas220

**Comment by Shreyas220** [comment]
i was trying this https://github.com/meshery/meshery-cpx/issues/63#event-4990769797 
but i encountered problem while importing meshkits
