### ISSUE TITLE
Move from `/api/experimental/oam` to `/api/oam`

### ISSUE THREAD

**Issue by utkarsh-pro** [meshery/meshery-istio#249]
**Current Behavior**
Currently istio adapter sends request to `/api/experimental/oam/workload` and `/api/experimental/oam/trait` in order to register its capabilities. 

**Desired Behavior**
https://github.com/meshery/meshery/pull/3542 will deprecate these endpoints in favour of  `/api/oam/workload` and `/api/oam/trait`. Istio adapter should adhere to the latest API changes in meshery server.

**Acceptance Tests**
- [ ] Replace all `/api/experimental/oam/workload` with `/api/oam/workload`
- [ ] Replace all `/api/experimental/oam/trait` with `/api/oam/trait`

**Comment by umairnsr87** [comment]
@utkarsh-pro Yes, I am willing to work on this...

**Comment by umairnsr87** [comment]
Thanks alot @utkarsh-pro !
