### ISSUE TITLE
Enhancing the way kubeopenapi-jsonschema is used in workflows

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery-istio#256]
**Description**
Currently inside of the workflow to generate components. The kubeopenapi-jsonschema repository is cloned,built( along with all the node modules) and after using it, a cleanup is done.

**Expected Behavior**
 @utkarsh-pro  has now packaged the node-modules inside of the binary itself hence the binary is self-sufficient. And we can get the binary directly from releases, so a better approach would be to fetch the binary directly without having to do all that npm installs, builds and cloning the entire repository.

**File I am referring to**
.github/workflows/update-oam-defs.yml

**Comment by piyushsingariya** [comment]
I would like to work on this, is it cool?

**Comment by Revolyssup** [comment]
> I would like to work on this, is it cool?

@DelusionalOptimist  what say?

**Comment by DelusionalOptimist** [comment]
Umm @piyushsingariya @Revolyssup I think this was for the current bash workflow, right? :thinking: 

Once https://github.com/meshery/meshery-istio/pull/269 gets in, we'll be making changes in this workflow such that we run and generate pattern components using the adapter's capability.
So these bash scripts will eventually go away and we'll be running adapter operations in this workflow instead which will internally take care of fetching jsonchema utility : )

**Comment by DelusionalOptimist** [comment]
I'll make sure to ping you @piyushsingariya once its ready so that you can work on the new workflow :smile:
