### ISSUE TITLE
[Lifecycle] use helm charts for installing istio

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery-istio#261]
**Current Behavior**
The adapter uses istioctl for installing Istio.

**Desired Behavior**
Move away from using istioctl and use helm charts instead.

---

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Revolyssup** [comment]
@DelusionalOptimist  using helm client binary? (with helm install and all)

**Comment by DelusionalOptimist** [comment]
@Revolyssup using helm binary, no no. CLI based operations tend to be a little fragile. They may end up changing their interface across versions. 

For e.g., currently the uninstall operation using istioctl goes like (and is hard-coded in the adapter), `istioctl x uninstall --set purge`. This command won't work with some earlier istio releases as it didn't exist for binaries at that time and there is a high probability that this won't work with later versions as well as `x` here implies experimental.

Its evident that we can't continue with this if we want to achieve multi version support in adapters, one of the destinations to which we are heading by generating pattern components (both at build time and runtime). :muscle: 

So we're trying to move away from using service mesh binaries directly and using helm charts which offer some long term control in this regard. For this purpose, we're using some '@utkarsh-pro-fueled' utilities from meshkit wrapping helm APIs. See: https://github.com/layer5io/meshkit/blob/master/utils/kubernetes/apply-helm-chart.go 

> In that case, from where would I find the charts apart from install the istio release and getting charts from there.

This concern is right. Getting the charts from istio release tars seems to be the only way for now as istio's release process is... a little unconventional. 

> If you could guide a little, I wanted to take up this issue. If you can, assign me too

Sorry :sweat_smile: I took this up myself and added it in https://github.com/meshery/meshery-istio/pull/262. 
But here is the thing, helm chart based installation has to be added to some other adapters as well. You should take a look at doing this in kuma adapter: https://github.com/layer5io/meshery-kuma
