### ISSUE TITLE
[CI] Failing Golang Tests

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-istio#278]
**Description**
See the following list of failed tests - 
https://github.com/meshery/meshery-istio/pull/274/checks?check_run_id=3573833308#step:5:198

**Expected Behavior**
All tests should be passing.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@Shreyas220 help, please - https://github.com/meshery/meshery-istio/runs/3699756795?check_suite_focus=true#step:5:475

**Comment by Shreyas220** [comment]
> @Shreyas220 are you still working on this?

no,
couldn't find the reason for failure

**Comment by leecalcote** [comment]
@Revolyssup will you wrangle this one?
