### ISSUE TITLE
Customizing URL and Method of dynamic component generation through environmental variables

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery-istio#291]
**Current Behavior**
At the below line, we have hardcoded the URL and generation method(Manifest or HELM) for dynamic component generation
https://github.com/meshery/meshery-istio/blob/74711eb2ea12d970ce3539d6a54a3f2ddd2dd0f6/main.go#L184

**Desired Behavior**
These should be further customizable by passing environmental variables. In absence of env variables, the current logic can be used as a fallback.

---
[Optional] **Alternatives**
A brief description of any alternative solutions or features you've considered.

[Optional] **Additional context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@Revolyssup Does this need reopened as a future enhancement or has this been addressed already?
