### ISSUE TITLE
[Cl] Make Slack Workflow Consistent

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery-istio#314]
#### Current Behavior

- Currently, the slack workflow (`.github/workflows/slack.yml` file) uses a hardcoded value for the repo name. 

#### Expected Behavior

- It should use a more generic name like `GITHUB_REPOSITORY` for the repo name.
- This would make the slack.yml file more consistent throughout all the Layer5 repositories.

Reference: https://docs.github.com/en/actions/learn-github-actions/environment-variables

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
Please assign me this issue, I'll like to work on it

**Comment by Mr-DG-Wick** [comment]
All yours @theBeginner86 😄

**Comment by leecalcote** [comment]
Thank you, gents!
