### ISSUE TITLE
[CI] Add newcomer-alert workflow

### ISSUE THREAD

**Issue by cpepper96** [meshery/meshery-istio#326]
**Current Behavior**
Currently there is no automated way of notifying the slack channel when a "good first issue" has been created.

**Desired Behavior**
Add newcomer-alert.yml to the Github workflow. 

---
**Resources**
Add the newcomer-alert.yml file to the .github/workflow folder.

Files needed:
https://github.com/layer5io/layer5/blob/master/.github/workflows/newcomers-alert.yml

**Comment by Ankita13-code** [comment]
Hi @cpepper96! I would like to take up this issue. Can you please assign it to me?

**Comment by cpepper96** [comment]
Hi @Ankita13-code unfortunately I can't assign this issue. Can another maintainer help us out? @leecalcote

**Comment by sayantan1413** [comment]
Done 🚀

**Comment by warunicorn19** [comment]
@Ankita13-code any updates on this?

**Comment by Ankita13-code** [comment]
I've opened a PR for this issue. Please have a look @warunicorn19
