### ISSUE TITLE
Provision: Expose and connect to Grafana

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-istio#33]
**Current Behavior**
When Istio is deployed with Meshery, users must manually expose the control plane's Grafana service.

**Desired Behavior**
When Istio is deployed with Meshery, the Grafana service in Istio's control plane should be exposed as a NodePort by default, but configurable to be exposed as a ClusterIP, LoadBalancer or NodePort. As Istio is deployed and Grafana service exposed, Meshery should automatically register the Grafana service's endpoint.

**Acceptance Criteria**
This enhancement is complete when:
- [ ] The Grafana service in Istio's control plane is configurable to be exposed as a NodePort, ClusterIP, or LoadBalancer. 
- [ ] NodePort is the default configuration setting.
- [ ] Meshery automatically registers the Grafana service's endpoint.

Existing behavior should also be true:
- [ ] Users are able to invoke an ad-hoc connectivity test with Grafana.
- [ ] Connectivity test retrieves Grafana version for display in a tooltip when the user hovers the mouse over the chip.
- [ ] Connectivity tests display either a success message: "Grafana successfully pinged!" or a failure message: "Could not connect to Grafana."

**Comment by ashiscs** [comment]
@lee sir, i think this issue is already addressed and needs to be closed?

**Comment by leecalcote** [comment]
@ashiscs thanks for checking. No, none of the **Acceptance Criteria** is completed, yet.

**Comment by leecalcote** [comment]
@vijcheru this builds on some of the work that you've done. What do you think about picking this one up?

**Comment by vijcheru** [comment]
Certainly, Lee. I've been involved in a few other things and so was not participating. I will go through the code and find out what I can.
