### ISSUE TITLE
[Lifecycle] Enhance error message for failed installations

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-istio#376]
#### Current Behavior

Meshery Server: stable-v0.6.0-rc-4
Meshery Adapter for Istio: stable-v0.5.25

An installation attempt failed as follows:

<img width="444" alt="Screen Shot 2022-01-31 at 8 55 35 AM" src="https://user-images.githubusercontent.com/7570704/151816814-dca0d4d5-64bc-4851-9000-34342e0270a7.png">

Logs from adapter:

```
mesheryctl system logs meshery-istio
Starting Meshery logging...
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:20:45Z" level=info msg="Adaptor Listening at port: 10000" app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:20:45Z" level=info msg="Registering static workloads with Meshery Server..." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:20:45Z" level=info msg="Registering latest components with Meshery Server" app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:20:45Z" level=info msg="Components available statically for version 1.12.2. Skipping dynamic component registeration" app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:21:53Z" level=info msg="Successfully registered static components with Meshery Server." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:54:04Z" level=info msg="Creating instance" app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:54:04Z" level=info msg="Listing Operations" app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:54:05Z" level=info msg="Creating instance" app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:54:47Z" level=info msg="Creating instance" app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:09Z" level=info msg="Creating instance" app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:09Z" level=info msg="Applying operation istio" app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:09Z" level=info msg="Looking for artifacts of requested version locally..." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:09Z" level=info msg="Artifacts not found..." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:09Z" level=info msg="Downloading requested istio version artifacts..." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:12Z" level=info msg="Installing using helm charts..." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	W0131 14:55:16.020694       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
meshery-istio-54f78f78-wlfdt	|	W0131 14:55:16.154890       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:17Z" level=error msg="context deadline exceeded" app=istio-adapter code=1025 probable-cause= severity=2 short-description="Error occured while applying Helm Chart" suggested-remediation=
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:17Z" level=info msg="Retrying to install using istioctl..." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:17Z" level=info msg="Installing using istioctl..." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:17Z" level=info msg="Looking for istioctl in the path..." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:17Z" level=info msg="Looking for istioctl in/root/.meshery/bin..." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:17Z" level=info msg="Using istioctl from the downloaded release bundle..." app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:17Z" level=info msg=Done app=istio-adapter
meshery-istio-54f78f78-wlfdt	|	time="2022-01-31T14:55:17Z" level=error msg="Error occured while installing istio mesh through istioctl." app=istio-adapter code=1003 probable-cause= severity=2 short-description="Error with istio operation" suggested-remediation=
meshery-istio-54f78f78-wlfdt	|
```

#### Desired Behavior
Can this message be enhanced to include an error code, so that the user can visit the Error Codes page and troubleshoot further? 

#### Implementation
1. Enhance the probable cause and suggested remediation for this error.
2. Include the Error Code in the message returned from Meshery Adapter to Meshery Server. Expose error code in the Notification Center.

#### Mockups
See https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=724%3A445

![Notification Center](https://user-images.githubusercontent.com/7570704/151817708-d7b75bf3-1d31-4cdb-b631-36f5e534de28.png)

#### Acceptance Tests
1. User can see probable cause and suggested remediation in Notification Center for this particular error.
    - See
1. User can click hyperlink in Notification Center message to visit the Error Code page in Meshery Docs.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by theBeginner86** [comment]
@leecalcote may I work on this?

**Comment by leecalcote** [comment]
That'd be great. Forewarning: this is a moderately-sized challenge.

**Comment by theBeginner86** [comment]
@leecalcote 

https://user-images.githubusercontent.com/73700530/154448965-c88b0dd3-c91a-42af-9259-cfbaffc84142.mov

Does this looks good? (Right now it works for failed installations/deletions of istio adapter only. For other adapters and other operations of Istio, the fields: probable cause, suggested remediation, and error code lookup shows `unavailable`.)

Should I raise a PR for this issue. I would have to raise it in 3 repos: meshery, meshery-adapter, istio

I had few question:
1. Will this enhanced error messages be used just for failed installations or for all failed operations? I'm asking this because every operations returns same Event structure, so it would be easier to reciprocate this in all operations' functions.
2. Will this be used by all adapters and for every failed operations?
