### ISSUE TITLE
Add end-to-end tests using bookinfo application

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery-istio#384]
#### Current Behavior

Currently e2e tests in the adapter only run tests for vanilla service mesh installation and for addons.
#### Desired Behavior

https://github.com/service-mesh-patterns/service-mesh-patterns/blob/master/samples/minimalistiobookinfo.yaml 
The above linked patternfile should also be deployed and assertions should be made.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by jbyers19** [comment]
@leecalcote, yes that would work. We use bookinfo, emojivoto, and online boutique sample apps for testing and demos, so they should work no problem.

**Comment by Revolyssup** [comment]
> @leecalcote, yes that would work. We use bookinfo, emojivoto, and online boutique sample apps for testing and demos, so they should work no problem.

Excellent! Should I assign you to the issue to have end to end tests in Nginx adapter by trying to deploy those applications in patternfile?

**Comment by jbyers19** [comment]
@Revolyssup, sure. Just a heads up though, it will probably be a while before I can get to it. I'm going to be mostly unavailable for the next couple weeks, but after that I'm hoping to be able to devote some time to finally getting the nginx adapter fully operational.

**Comment by Revolyssup** [comment]
@AugustasV  Do you still want to work on it?

**Comment by AugustasV** [comment]
@Revolyssup yes
