### ISSUE TITLE
Meshery-istio image doesnt work for arm64

### ISSUE THREAD

**Issue by pdsouza01** [meshery/meshery-istio#451]
#### Current Behavior
Pods doesn't come up with image : 
https://hub.docker.com/layers/layer5/meshery-istio/stable-latest/images/sha256-1fea8fd2cbf4d91298899a99d93285c339815866ad0f8833b3d34a0e85da222e?context=explore

I debugged it and looks like the image in dockerhub ([https://hub.docker.com/layers/layer5/meshery-istio/stable-latest/images/sha256-1fea8[…]99a99d93285c339815866ad0f8833b3d34a0e85da222e?context=explore](https://hub.docker.com/layers/layer5/meshery-istio/stable-latest/images/sha256-1fea8fd2cbf4d91298899a99d93285c339815866ad0f8833b3d34a0e85da222e?context=explore)) for arm is build with amd64 tag

#### Screenshots/Logs

**kubectl get pods -n meshery**
NAME                                    READY   STATUS             RESTARTS   AGE
meshery-app-mesh-d8bb6fb98-26lgd        0/1     CrashLoopBackOff   300        25h
meshery-cilium-77c894d948-ksp5h         0/1     CrashLoopBackOff   300        25h
meshery-consul-c4f966fb-d424r           0/1     CrashLoopBackOff   300        25h
meshery-dbcf8bbc9-gwmmn                 0/1     CrashLoopBackOff   301        25h
meshery-istio-54f78f78-9qshc            0/1     CrashLoopBackOff   300        25h
meshery-kuma-66fb8d8fb9-pvf6w           1/1     Running            0          25h
meshery-linkerd-747f88f674-ws6zr        0/1     CrashLoopBackOff   300        25h
meshery-nginx-sm-78b6dd775d-b6shd       0/1     CrashLoopBackOff   300        25h
meshery-nsm-578546d5c6-ldg9x            0/1     CrashLoopBackOff   300        25h
meshery-operator-586c6f895d-vs4l8       0/2     CrashLoopBackOff   600        25h
meshery-osm-5cb545d586-k7njp            1/1     Running            0          25h
meshery-traefik-mesh-747f68fc68-7d8nh   0/1     CrashLoopBackOff   300        25h

**kubectl describe pod meshery-istio-54f78f78-9qshc -n meshery**
Name:         meshery-istio-54f78f78-9qshc
Namespace:    meshery
Priority:     0
Node:         node01.local
Start Time:   Thu, 07 Jul 2022 12:53:13 -0700
Labels:       app.kubernetes.io/instance=meshery
app.kubernetes.io/name=meshery-istio
pod-template-hash=54f78f78
Annotations:  <none>
Status:       Running
IP:           10.42.0.141
IPs:
IP:           10.42.0.141
Controlled By:  ReplicaSet/meshery-istio-54f78f78
Containers:
meshery-istio:
Container ID:   docker://853944c0a049687c1b4cffd44604d2d8f2894ad3ede098c4d2461da46ab0b45d
Image:          layer5/meshery-istio:stable-latest
Image ID:       docker-pullable://layer5/meshery-istio@sha256:18e226886f2f10b0f076dbf02b1b5ac569d2fb54e317414086178c904557e0e1
Port:           10000/TCP
Host Port:      0/TCP
State:          Waiting
Reason:       CrashLoopBackOff
Last State:     Terminated
Reason:       Error
Exit Code:    1
Started:      Fri, 08 Jul 2022 14:11:06 -0700
Finished:     Fri, 08 Jul 2022 14:11:06 -0700
Ready:          False
Restart Count:  301
Environment:    <none>
Mounts:
/var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7m897 (ro)
Conditions:
Type              Status
Initialized       True
Ready             False
ContainersReady   False
PodScheduled      True
Volumes:
kube-api-access-7m897:
Type:                    Projected (a volume that contains injected data from multiple sources)
TokenExpirationSeconds:  3607
ConfigMapName:           kube-root-ca.crt
ConfigMapOptional:       <nil>
DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
Type     Reason            Age                     From     Message
----     ------            ----                    ----     -------
Warning  DNSConfigForming  4m24s (x7254 over 25h)  kubelet  Search Line limits were exceeded, some search paths have been omitted, the applied search l
ine is: meshery.svc.rke.rancher-local svc.rke.rancher-local rke.rancher-local 

**kubectl logs meshery-istio-54f78f78-9qshc -n meshery**
exec /meshery-istio: exec format error

#### Environment

- **Host OS:** Linux
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-latest

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you, @pdsouza01 :thu

**Comment by leecalcote** [comment]
Notes from @Revolyssup:

> [@Preema Merlin Dsouza](https://layer5io.slack.com/team/U03NX1XJ13N) Thank you for catching this one!
> I just noticed that it is because inside the Dockerfile, OS/Arch is hardcoded [here](https://github.com/meshery/meshery-istio/blob/c779f0fb9fc5a614dbea671b77558ddf55be6c18/Dockerfile#L18) and [here](https://github.com/meshery/meshery-istio/blob/c779f0fb9fc5a614dbea671b77558ddf55be6c18/Dockerfile#L33).
> It should be passed as a build argument inside the workflow [here](https://github.com/meshery/meshery-istio/blob/c779f0fb9fc5a614dbea671b77558ddf55be6c18/.github/workflows/multi-platform.yml#L106) and the Dockerfile needs to be updated accordingly.

This issue is up for grabs.

**Comment by leecalcote** [comment]
@pdsouza01 will you be tomorrow's [CI meeting](https://meshery.io/calendar)? If so, let's be sure that this gets on the agenda.

**Comment by AugustasV** [comment]
I will look what I can do about it

**Comment by pdsouza01** [comment]
@AugustasV Could you please let me know the build label which has this fix , I would like to test it on ARM

**Comment by AugustasV** [comment]
@pdsouza01 what about now? Right now I only spot errors on consul
![image](https://user-images.githubusercontent.com/7377334/185759688-db1443d2-9387-44d1-8f89-f597d2af5a92.png)

**Comment by AugustasV** [comment]
It works as expected. Create new issue if problem still persist.
