### ISSUE TITLE
[Docs] README: Light Mode / Dark Mode support

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-istio#465]
**Current Behavior**
This repo's readme.md (https://github.com/layer5io/layer5#readme) assumes light mode visitors.

**Desired Situation**
Use GitHub's relatively new ability to [define light and dark mode images](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) in markdown for each of the logos.

Find light and dark mode flavors of each of the logos here: https://layer5.io/brand or in the shared, community drive.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by jmutton2** [comment]
Hello! 

I've just started contributing and was looking for some feedback. 

I started with this issue and can't seem to find any resources for the Community/Contributions icon or the Service Mesh Interface Conformance icon.

Do you want me to remake these icons with a gray scale theme?

Thanks!

Here's what I have so far:

![image](https://user-images.githubusercontent.com/55411119/182685228-38ad1197-dbe2-4a1e-ad68-37e7e6d4e1cb.png)
![image](https://user-images.githubusercontent.com/55411119/182685397-65be3b0f-d9a0-4271-99e2-f9c035dbe535.png)

**Comment by leecalcote** [comment]
Looking good. Will you kindly use the filled, white version of the Meshery Operator (vs the outline version)? You’re right: there isn’t a white version of the SMI Conformance icon, yet. Yes, if you would like to attempt to make one, that would be great. Please see the community’s shared Google Drive for additional assets. Note: we shy away from using grayscale, but instead use reduce or increase opacity levels from a base of #FFFFFF to give a grayscale-like effect, but in (hopefully) more attractive way.

**Comment by leecalcote** [comment]
@legendarykamal is this something that you can take on?

**Comment by legendarykamal** [comment]
Sure @leecalcote 🙂

**Comment by legendarykamal** [comment]
@leecalcote if this is about layer5.io then it has already been fixed for dark mode, we had decided to use the green images.

**Comment by leecalcote** [comment]
Sounds good, @legendarykamal. 

Likely, I originally opened this issue under the wrong repo or neglected to under the issue description with the Istio adapter’s info. Will you do me a favor and review this repos read me for light and dark mode support? Also, let’s do away with use of the Meshery logo with the tagline and instead use the logo with no tagline.

**Comment by NPDebs** [comment]
Ahem! Did someone say light and dark mode? 😃🙃

Mr @leecalcote & @legendarykamal , mind if I jump in? 👀

**Comment by legendarykamal** [comment]
oh I think I forgot to file the PR for this. So just saving your efforts @NPDebs , I will do this by today 😄 .

**Comment by NPDebs** [comment]
Dang it! 😭😫

Sure @legendarykamal . Time to find more repos that attention. 🏃🏽‍♀️

**Comment by legendarykamal** [comment]
checkout the integrations needed on layer5 they need attention  @NPDebs 🦩
