### ISSUE TITLE
Provisioning failure with istioctl

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-istio#486]
### Current Behavior

<img width="590" alt="Screen Shot 2022-09-22 at 12 24 02 PM" src="https://user-images.githubusercontent.com/7570704/191891074-b23de118-76eb-4017-94cb-ce8ec2a34b39.png">

### Screenshots/Logs
```
$ k logs -f -n meshery meshery-istio-6fd848744c-9ptvq
time="2022-09-23T16:00:36Z" level=info msg="Adaptor Listening at port: 10000" app=istio-adapter
time="2022-09-23T16:00:36Z" level=info msg="Registering latest components with Meshery Server" app=istio-adapter
time="2022-09-23T16:00:36Z" level=info msg="Components available statically for version 1.15.0. Skipping dynamic component registeration" app=istio-adapter
time="2022-09-23T16:00:36Z" level=info msg="Registering static workloads with Meshery Server..." app=istio-adapter
time="2022-09-23T16:00:56Z" level=info msg="Successfully registered static components with Meshery Server." app=istio-adapter
```

### Environment

- **Host OS:** Mac
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.6.8
- **Meshery Adapter Version:** stable-v0.6.1

### Documentation Issue

There is no suggested remediation for this issue either:

<img width="797" alt="Screen Shot 2022-09-23 at 2 58 51 PM 2" src="https://user-images.githubusercontent.com/7570704/192047817-3aa0c4d9-24e2-4583-bf5c-a6319747b344.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
There are no logs in the Istio adapter either (in the stable release) that I can provide. No logs tracking the provisioning request.

Is the adapter not failing over to alternative provisioning methods?

**Comment by Revolyssup** [comment]
> 

This cannot be the case. The error that is thrown here will definitely be logged in the adapter. Can you make sure that Meshery server is connected to the exact same adapter pod on which the logs are seen here.
For the second question, the default method is "helm chart", istioctl is fallback

**Comment by Revolyssup** [comment]
I can confirm that on both edge and release, installation is working fine. In this specific issue, I would need the logs of the adapter which actually served this request because the adapter in the screenshot didn't. There has to be a debug log whenever a meshops or patternops request is recieved.

**Comment by leecalcote** [comment]
Let's close out this issue given the missing info and the inability to reproduce. Thanks for digging in here.

**Comment by leecalcote** [comment]
Here's a related, but inverted issue with helm deployment - #497
