### ISSUE TITLE
[CI] Update Multi Platform build and Release workflow

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery-istio#493]
#### Current Behavior

Currently, the [multiplatform.yml](https://github.com/meshery/meshery-istio/blob/master/.github/workflows/multi-platform.yml) file is sending unwanted build arguments to docker build process because of which release tag and commit_sha are not being passed over to the image and hence the version of meshery adapter are not visible on-hovering adapters chips on Meshery UI Dashboard.

#### Desired Behavior

This would be fixed when correct build args are passed to the docker build step inside multiplatform workfow.
Required Args:
- VERSION
- GIT_COMMITSHA

Check this commit for reference:
https://github.com/meshery/meshery-consul/commit/446ad170c938c9bfe22e6e8710459d63395b9148

related to: https://github.com/meshery/meshery/issues/6245

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Goodiec** [comment]
@theBeginner86, can I work on this issue?

**Comment by theBeginner86** [comment]
@Goodiec, I believe by mistake you created your PR onto your fork. Will you see that the PR is created for this repo?


> For reference, you can refer to this contributing guide: https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md

**Comment by acald-creator** [comment]
@Goodiec Have you been able to submit a new PR to this repo with your changes?

**Comment by Goodiec** [comment]
> @Goodiec Have you been able to submit a new PR to this repo with your changes?

Done. My apologies, just saw this.
