### ISSUE TITLE
[CI] Change `Components-to-Doc` Workflow to account for `meshmodels/components` and drop using oam

### ISSUE THREAD

**Issue by gopivaibhav** [meshery/meshery-istio#528]
#### Current Behavior

[This](https://github.com/meshery/meshery-istio/blob/master/.github/workflows/components-to-doc.yml) workflow is checking the `templates/oam/workloads` directory

#### Desired Behavior

We need to make sure that the [paths](https://github.com/meshery/meshery-istio/blob/master/.github/workflows/components-to-doc.yml#L5) should look at `templates/meshmodel/components` as the oam is going to be deprecated and the job of workflow should remain same

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@asubedy fyi

**Comment by siddhikhapare** [comment]
@leecalcote I would like to work on this issue.

**Comment by leecalcote** [comment]
@gopivaibhav are you working on this?

**Comment by gopivaibhav** [comment]
> @gopivaibhav are you working on this?

Not yet started as I have other tasks to complete. You can assign it to @siddhikhapare

**Comment by leecalcote** [comment]
There's not enough context here for her to reasonably understand and complete it. If you'll be offering direction, that's great.

**Comment by gopivaibhav** [comment]
> There's not enough context here for her to reasonably understand and complete it. If you'll be offering direction, that's great.

Afaik, we have to change the path as I have mentioned in the issue and make sure that the action is not going to be changed (Have to look at the things performed in the workflow) and for guidance I didn't really go through this workflow. 
Probably @Revolyssup has more understanding of what exactly @siddhikhapare has to do.

**Comment by siddhikhapare** [comment]
@leecalcote @Revolyssup Here to resolve issue only folder path need to add. Is there anything else require to add?

**Comment by asubedy** [comment]
@siddhikhapare yes Instead of path being `templates/oam/workloads` the path should be `templates/meshmodel/components`

**Comment by leecalcote** [comment]
Thanks for this guidance, @asubedy. @siddhikhapare does this make sense?

**Comment by asubedy** [comment]
Issue solved by #531. Closing the issue.
