### ISSUE TITLE
Move from ISTIO to Istio in model components

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-istio#609]
<@U02T9JKCRLG> when you get the Meshery Adapters registering their components again, will you please see that “ISTIO” change to “Istio” in the Istio adapter’s components?

[Slack Message](https://layer5io.slack.com/archives/C017NA80S66/p1692045330887179)

### Implementation:

1. Find "ISTIO" and replace with "Istio".

### Acceptance Test:

1. Meshery Adapter registers components with Meshery Server.
1. User is able to provision Istio when using the renamed components.

**Comment by MUzairS15** [comment]
@Freedisch Let me know if you have difficulty understanding the issue.
