### ISSUE TITLE
[chore] update Go to 1.21, and update relevant pkgs

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery-istio#621]
### Desired Behaviour
Need to update `Go` to `1.21` in `go.mod` and in `Dockerfile`, and also `Makefile`

- Minor chore on updating `meshkit` and `meshery-adapter-library`

**Comment by cp-Coder** [comment]
Hi I would like to work on this issue.

**Comment by hemantmm** [comment]
Hi, @Ghat0tkach could I take up this issue?

**Comment by I-MirzaBaig** [comment]
Is this issue, still on?
If not, can i work on this?

**Comment by hemantmm** [comment]
@saurabh100ni would like to work on this issue?

**Comment by vansh106** [comment]
Can I work on this issue?

**Comment by leecalcote** [comment]
Oh, I see there's a PR open against this issue - https://github.com/meshery/meshery-istio/pull/622.

**Comment by vansh106** [comment]
I believe its resolved, I'll find any other issue

> Oh, I see there's a PR open against this issue - #622.
