### ISSUE TITLE
[CI] e2e-test adaptersv2 always failed on `runresources` step

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery-istio#628]
#### Current Behavior

https://github.com/meshery/meshery-istio/actions/workflows/e2etests.yml

Here is the code https://github.com/meshery/meshery/blob/adf27cfc8f1a9c6d02e1cc0351c66757a8bcab3c/.github/workflows/test_adaptersv2.yaml#L262-L272

There is lots of the Shell script to check the resources are already exist or not. And update the `existatus`. However, the `existatus` is always 1, and it means the resources are always failed to start to run. 

```
Run if [ "$exitstatus" -eq 1 ];then
  if [ "$exitstatus" -eq 1 ];then
      exit 1
  fi
  shell: /usr/bin/bash -e {0}
  env:
    MINIKUBE_HOME: /home/runner/work/_temp
    exitstatus: 1
Error: Process completed with exit code 1.
```

#### Desired Behavior

The `runresources` step should be more reliable

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Aisuko** [comment]
https://layer5io.slack.com/archives/C011VPREG2Z/p1696837655199399

**Comment by yash37158** [comment]
Hey @Aisuko, to address the reliability issue and ensure that it is correctly handled we can handle the resource status check. by assuming that we want to check the status of multiple resources and mark the workflow as failed if any critical resource fails while still allowing the workflow to continue in other cases. 

This approach should make our workflow more reliable and better handle resource status checks while allowing us to continue with the workflow in cases where some non-critical resources might not be in the "Running" state.
