### ISSUE TITLE
[CI] Failing E2E test

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery-istio#645]
#### Current Behavior
https://github.com/meshery/meshery-istio/actions/runs/6932844139

#### Expected Behavior

All tests should pass for latest Meshery Adapter for Istio Service Mesh.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by vaibhavpnimkar** [comment]
is this still open i would like to work on this !!

**Comment by theBeginner86** [comment]
> is this still open i would like to work on this !!

@vaibhavpnimkar 
Yes, its available. Would you mind confirming the approach or your findings so far?

**Comment by vaibhavpnimkar** [comment]
Cant start  right now. would you mind if i start next week ???

**Comment by MUzairS15** [comment]
https://github.com/meshery/meshery-istio/actions/runs/7522577044/job/20474864059

**Comment by MUzairS15** [comment]
@aeswibon Would you like to take up?

**Comment by shourya2002-geek** [comment]
Hi, can I be assigned this issue, if no one has been assigned yet ?

**Comment by aeswibon** [comment]
> @aeswibon Would you like to take up?

Sure

**Comment by MUzairS15** [comment]
@shourya2002-geek updates?

**Comment by shourya2002-geek** [comment]
> @shourya2002-geek updates?

Hi @MUzairS15 , the issue has not been assigned to me yet. Could you assign to me ?

**Comment by leecalcote** [comment]
Let's rock 'n roll...

**Comment by singh1203** [comment]
@shourya2002-geek are you still working on it? -cc @theBeginner86

**Comment by singh1203** [comment]
@leecalcote Please assign me, the last step out of 3 is left to be done from my side.
