### ISSUE TITLE
Ensure Consistent Use of MeshKit Errors in Meshery-Istio.

### ISSUE THREAD

**Issue by singh1203** [meshery/meshery-istio#679]
#### Current Behavior

Currently, there are instances where errors are being used directly instead of MeshKit errors, which impacts the consistency and quality of error reporting across the project.

#### Desired Behavior

- [ ] Replace all direct usages of errors with MeshKit errors.
- [ ] Ensure that each MeshKit error includes:- Short Description, Long Description, Probable Cause & Suggested Remediation.

#### References
[Meshery Documentation on Meshkit](https://docs.meshery.io/project/contributing/contributing-error)

- Make sure to follow these guidelines during writing Meshkit errors
https://discuss.layer5.io/t/best-practices-for-writing-meshkit-errors/5536

- Also here is an example PR to which you can refer:
[#11340](https://github.com/meshery/meshery/pull/11340)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by thedeeppp** [comment]
I would like to work on this issue but may need some help

**Comment by singh1203** [comment]
> I would like to work on this issue but may need some help

Hey @thedeeppp, don't forget to post your question in the discussion forum or in Slack.

**Comment by ShivanshuGupta07** [comment]
@singh1203 , is the above task done or can you please provide some direct helping resources so that I can give it a try?

**Comment by singh1203** [comment]
@ShivanshuGupta07 @thedeeppp Thanks for waiting. Here's the [Meshery Docs](https://docs.meshery.io/project/contributing/contributing-adapters) for running the adapter in your local development environment. Let me know if you need further guidance.

**Comment by ShivanshuGupta07** [comment]
@singh1203 ,
1. can you elaborate on what exactly is required?
2.  where the changes are need to do this task, and how can we verify if the task is completed or not?
3. Can you elaborate how to replicate current behaviour in my local?
4. Is there any video for reference?

**Comment by ShivanshuGupta07** [comment]
Sorry, by mistake I unassigned myself, @singh1203 can you please reassign me
